---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - import  

env:
  node: true
  es6: true
  browser: true  

extends:
  - 'airbnb-base'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  no-console: 'off'
  import/extensions: 'off'